cycle_2020/urls.py
from django.urls import include, path, re_path
from rest_framework import routers, serializers, viewsets
from cycle_2020 import views
from cycle_2020.bloomberg_views import summary, summary_csv, cycle_summary, cycle_summary_csv
from cycle_2020.api import *

app_name = 'cycle_2020'

router = routers.DefaultRouter()
router.register(r'filings', FilingViewSet, basename=Filing)


API = [path('api/v1/', include(router.urls))]


urlpatterns = API + [
        path('', views.index, name='index'),
        re_path(r'filings/$', views.filings, name='filings'), #we might someday want a real index but good enough for now
        re_path(r'cycle_summary/$', cycle_summary, name='cycle_summary'),
        re_path(r'cycle_summary_csv/$', cycle_summary_csv, name='cycle_summary_csv'),
        re_path(r'summary/$', summary, name='summary'),
        re_path(r'summary_csv/$', summary_csv, name='summary_csv'),
        re_path(r'contributions/$', views.contributions, name='contributions'),
        re_path(r'contributions_csv/$', views.contributions_csv, name='contributions_csv'),
        re_path(r'expenditures/$', views.expenditures, name='expenditures'),
        re_path(r'expenditures_csv/$', views.expenditures_csv, name='expenditures_csv'),
        re_path(r'ies/$', views.ies, name='ies'),
        re_path(r'ie_csv/$', views.ie_csv, name='ie_csv'),
        path('races', views.races, name='races'),
        path('top_donors', views.top_donors, name='top_donors'),
        path('filing_status/<str:status>', views.filing_status, name='filing_status'),
        path('committee/<str:committee_id>', views.committee, name='committee'),
        re_path(r'candidates/$', views.candidates, name='candidates'),
        re_path(r'candidates_csv/$', views.candidates_csv, name='candidates_csv'),
        re_path(r'inaugural/$', views.inaugural, name='inaugural'),
        re_path(r'presidential_csv/$', views.presidential_csv, name='presidential_csv')

    ]

donor/urls.py
from django.urls import include, path, re_path
from donor import views

app_name = 'donor'

urlpatterns = [
        path('donor_details/<int:donor_id>', views.donor_details, name='donor_details')
    ]

urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    path('2020/', include('cycle_2020.urls', namespace='2020')),
    path('2022/', include('cycle_2022.urls', namespace='2022')),
    path('2024/', include('cycle_2024.urls', namespace='2024')),
    path('donor/', include('donor.urls', namespace='donor')),

]

urlpatterns += staticfiles_urlpatterns()

templates/2024/base.html
{% extends 'base.html' %}

{% block navbar %}

 <div class="navbar navbar-default navbar-primary">
      <div class="container">
        <div class="navbar-header">
          <div class="logo-links__bloomberg"></div>
          
          <a class="navbar-brand" href="/2024">FEC 2024</span></a>
        </div>
         <ul class="nav navbar-nav navbar-right navbar-bits">
          <li><a href="{%url '2024:summary'%}">Summaries</a></li>
          <li><a href="{%url '2024:contributions'%}">Receipts</a></li>
          <li><a href="{%url '2024:expenditures'%}">Expenditures</a></li>
          <li><a href="{%url '2024:ies'%}">IEs</a></li>
          <li><a href="{%url '2024:races'%}">Races</a></li>
          <li><a href="{%url '2024:candidates'%}">Candidates</a></li>
          <li><a href="http://indgdatadesk.com/docs/">Help</a></li>
        </ul>

      </div>
    </div>

<div id="content" class="container">
      {% block content %}{% endblock %}
</div>

{% endblock %}

templates/2024/candidates.html
{% extends '2024/base.html' %}
{% load humanize %}
{% load admin_urls %}


{% block content %}

<h2> Candidates </h2>
<h5> Results as of {% if deadline %} {% if deadline|length == 8 %} {{deadline|slice:"4:6"}}/{{deadline|slice:"6:8"}}/{{deadline|slice:"0:4"}} {% else %} {{deadline}}{%endif%} {% else %} most recent available filing {% endif %} </h5>

 <div class="text-right">
        <a href="{{csv_url}}">Download as CSV</a>
    </div>
<table class="table">
    <tr>
        <th> Name </th>
        <th> District </th>
        <th> Total Receipts </th>
        <th> Cash on hand</th>
        <th> Unitemized </th>
        <th> From candidate </th>
        <th> As of date </th>
        <th> Filed at </th>

    </tr>
    {% for candidate, filing in candidates %}
    <tr>
        <td> {{candidate.name}} </td>

        <td> {{candidate.district}} </td>

        {% if filing %}
        
            <td class="text-right">
                    ${{filing.cycle_total_receipts|floatformat:2|intcomma}}
            </td>

            <td class="text-right">
                    ${{filing.cash_on_hand_close_of_period|floatformat:2|intcomma}}
            </td>
            <td class="text-right">
                    ${{filing.cycle_individuals_unitemized|floatformat:2|intcomma}}
            </td>
            <td class="text-right">
                    ${{filing.cycle_candidate_donations_plus_loans|floatformat:2|intcomma}}
            </td>
            <td>
                    {% if filing.coverage_through_date|length == 8 %} {{filing.coverage_through_date|slice:"4:6"}}/{{filing.coverage_through_date|slice:"6:8"}}/{{filing.coverage_through_date|slice:"0:4"}} {% else %} {{filing.coverage_through_date}}{%endif%}
            </td>
            <td>{{filing.created}} </td>

        {% else %}
            <td>NA</td> <td>NA</td> <td>NA</td> <td>NA</td> <td>NA</td> <td>NA</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>



{% endblock %}

templates/2024/committee.html
{% extends '2024/base.html' %}
{% load humanize %}


{% block content %}


<h2> {{committee.committee_name}} </h2>

<div class="row">
<dl>
    <dt>Cycle total receipts</dt>
    <dd><a href="{%url '2024:contributions'%}?committee={{committee.fec_id}}">${{most_recent_periodic.cycle_total_receipts|floatformat:2|intcomma}}</a></dd>

    <dt>Cycle total disbursements</dt>
    <dd><a href="{%url '2024:expenditures'%}?committee={{committee.fec_id}}">${{most_recent_periodic.cycle_total_disbursements|floatformat:2|intcomma}}</a></dd>
</dl>
</div>
<div class="row">
    <h3>Periodic filings</h3>
</div>
<div class="row">
<table class="table">
<tr>
    <th>Form type</th>
    <th>Period start</th>
    <th>Period end</th>
    <th>Receipts</th>
    <th>Expends</th>
    <th>Cash</th>
    <th>Debts</th>
</tr>
{% for filing in periodic %}
<tr>
    <td class="text-right"> <a href="{{filing.url}}">{{ filing.form_type }}</a></td>
    <td> {{ filing.coverage_from_date }}</td>
    <td> {{ filing.coverage_through_date }}</td>
    <td class="text-right"> <a href="{%url '2024:contributions'%}?filing_id={{filing.filing_id}}">${{ filing.period_total_receipts|floatformat:2|intcomma }}</a></td>
    <td class="text-right"> <a href="{%url '2024:expenditures'%}?filing_id={{filing.filing_id}}">${{ filing.period_total_disbursements|floatformat:2|intcomma }}</a></td>
    <td class="text-right">${{ filing.cash_on_hand_close_of_period|floatformat:2|intcomma }}</td>
    <td class="text-right"> ${{ filing.debts_by_summary|floatformat:2|intcomma }}</td>
</tr>
{% endfor %}

</table>
</div>
<div class="row">
    <h3>Other filings</h3>
</div>
<div class="row">
<table class="table">
<tr>
    <th>Form type</th>
    <th>Date Signed</th>
    <th>IEs</th>

</tr>
{% for filing in non_periodic %}
<tr>
    <td> {{ filing.form_type }}</td>
    <td> {{ filing.date_signed }}</td>
    <td class="text-right"> <a href="{%url '2024:ies'%}?filing_id={{filing.filing_id}}">
            {% if filing.form == 'F24' %}
          ${{filing.computed_ie_total_for_f24|floatformat:2|intcomma}}
        {% else %}
          ${{filing.period_independent_expenditures|floatformat:2|intcomma}}
        {% endif %}
    </a></td>
</tr>
{% endfor %}


</table>
</div>

{% endblock %}

templates/2024/contributions.html
{% extends '2024/base.html' %}
{% load humanize %}


{% block content %}

<h2> Search for receipts </h2>
<div class="row">
<form action="/2024/contributions/" method="get">
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>


<div class="row">
{% if results %}
<div class="page-header row">
  <div class="header-title">
    {% if results_sum %}
    <h2> Receipts total: ${{results_sum.contribution_amount__sum|floatformat:2|intcomma}} </h2>
    This total includes only itemized receipts.
    {% endif %} 
    <div class="text-right">
        <a href="{{csv_url}}">Download as CSV</a>
    </div>
    </div>
</div>
  <table class="table table-bordered table-striped">
    <tr>
        <th> Committee </th>
        <th> Contributor name </th>
        <th> Address </th>
        <th> Employer </th>
        <th> Occupation </th>
        <th> Amount </th>
        <th> Date </th>
        <th> Line Type </th>
    </tr>
    {% for result in results %}
    <tr>
        <td>{{result.committee_name}}</td>
        <td>{{result.contributor_name}}</td>
        <td>{{result.address}}</td>
        <td>{{result.contributor_employer}}</td>
        <td>{{result.contributor_occupation}}</td>
        <td>${{result.contribution_amount|floatformat:2|intcomma}}</td>
        <td>{{result.contribution_date_formatted|date:"SHORT_DATE_FORMAT"}}</td>
        <td>{{result.form_type}}</td>
    </tr>
  {% endfor %}
</table>
</div>

{% include 'pagination.html' %}

{% endif %}


{% endblock %}

templates/2024/cycle_summary.html
{% extends '2024/base.html' %}
{% load humanize %}
{% load admin_urls %}


{% block content %}


<h2> Search for totals by cycle </h2>
<h3>
{% if request.GET %}
<a href="{{ period_summary_url }}">(Repeat previous search for totals by reporting period)
{% else %}
<a href="{{ period_summary_url }}">(Search instead for totals by reporting period)
{% endif %}
</a>
</h3>
<div class="row">
<form action="/2024/cycle_summary/" method="get">
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>

<div class="row">
<div class="page-header row">
  <div class="header-title">
    <div class="text-right">
        <a href="{{csv_url}}"><p/>Download as CSV</a>
    </div>
    </div>
</div>

<table class="table">
    <tr>
        <th> Name </th>
        <th> Filing Type </th>
        <th> Coverage Period</th>
        <th> Cycle Individual<br/ >Contributions</th>
        <th> Cycle Disbursements </th>
        <th> Cycle Receipts </th>
        <th> Cycle Itemized<br/ >Contributions</th>
        <th> Cycle Unitemized<br/ >Contributions</th>
        <th title="Unitemized / Total Contributions * 100"> Cycle Percent<br/ >Unitemized<br/ >of Total</th>
        <th title="Disbursements / Receipts * 100"> Cycle Burn Rate </th>
        <th> Cash </th>
        <th> IEs </th>
        <th> Filing date </th>
    </tr>
    {% for filing in results %}
    <tr>
        <td> <a href="{%url '2024:committee' filing.filer_id%}">{{filing.committee_name}}</a> </td>
        <td> <a href="{{filing.url}}">{{filing.form}}</a> {% if filing.amends_filing %} (AMENDMENT) {% endif %} </td>
        <td> {% if filing.coverage_from_date|length == 8 %} {{filing.coverage_from_date|slice:"4:6"}}/{{filing.coverage_from_date|slice:"6:8"}}/{{filing.coverage_from_date|slice:"0:4"}} {% else %} {{filing.coverage_from_date}}{%endif%} - 
        {% if filing.coverage_through_date|length == 8 %} {{filing.coverage_through_date|slice:"4:6"}}/{{filing.coverage_through_date|slice:"6:8"}}/{{filing.coverage_through_date|slice:"0:4"}} {% else %} {{filing.coverage_through_date}}{%endif%}
        
        </td> 
        <td>${{filing.cycle_individual_contribution_total|floatformat:2|intcomma}} </td>
        <td> <a href="{%url '2024:expenditures'%}?filing_id={{filing.filing_id}}">${{filing.cycle_total_disbursements|floatformat:2|intcomma}}</a> </td>
        <td> <a href="{%url '2024:contributions'%}?filing_id={{filing.filing_id}}">${{filing.cycle_total_receipts|floatformat:2|intcomma}}</a>
            {% if filing.cycle_total_receipts > 99999 %}
                (<a href="{% url opts|admin_urlname:'changelist' %}?q={{filing.filing_id}}">Link donors</a>)
                
            {% endif %}
        </td>
        <td> ${{filing.cycle_individuals_itemized|floatformat:2|intcomma}} </td>
        <td> ${{filing.cycle_individuals_unitemized|floatformat:2|intcomma}} </td>
        <td> {{filing.cycle_percent_unitemized|floatformat:1|intcomma}}% </td>
        <td> {{filing.cycle_disbursements_div_receipts|floatformat:1|intcomma}}% </td>
        <td> ${{filing.cash_on_hand_close_of_period|floatformat:2|intcomma}} </td>
        <td> <a href="{%url '2024:ies'%}?filing_id={{filing.filing_id}}">
        {% if filing.form == 'F24' %}
          ${{filing.computed_ie_total_for_f24|floatformat:2|intcomma}}
        {% else %}
          ${{filing.cycle_independent_expenditures|floatformat:2|intcomma}}
        {% endif %}
        
        
    </a> </td>
        <td> {% if filing.date_signed|length == 8 %} {{filing.date_signed|slice:"4:6"}}/{{filing.date_signed|slice:"6:8"}}/{{filing.date_signed|slice:"0:4"}} {% else %} {{filing.date_signed}}{%endif%}</td>   
    </tr>
    {% endfor %}
</table>

{% include 'pagination.html' %}

        

{% endblock %}

templates/2024/expenditures.html
{% extends '2024/base.html' %}
{% load humanize %}


{% block content %}

<h2> Search for expenditures </h2>
<div class="row">
<form action="/2024/expenditures/" method="get">
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>


<div class="row">
{% if results %}
 
<div class="page-header row">
  <div class="header-title">
    {% if results_sum %}
    <h2> Expenditures total: ${{results_sum.expenditure_amount__sum|floatformat:2|intcomma}} </h2>
    This total includes only itemized expenditures.
    {% endif %}
    <div class="text-right">
        <a href="{{csv_url}}">Download as CSV</a>
    </div>

    </div>
</div>
  <table class="table table-bordered table-striped">
    <tr>
        <th> Committee </th>
        <th> Recipient name </th>
        <th> Address </th>
        <th> Purpose </th>
        <th> Amount </th>
        <th> Date </th>
        <th> Line Type </th>
    </tr>
    {% for result in results %}
    <tr>
        <td>{{result.committee_name}}</td>
        <td>{{result.payee_name}}</td>
        <td>{{result.address}}</td>
        <td>{{result.expenditure_purpose_descrip}}</td>
        <td>${{result.expenditure_amount|floatformat:2|intcomma}}</td>
        <td>{{result.expenditure_date_formatted|date:"SHORT_DATE_FORMAT"}}</td>
        <td>{{result.form_type}}</td>
    </tr>
  {% endfor %}
</table>
</div>

{% include 'pagination.html' %}

{% endif %}


{% endblock %}

templates/2024/filing_status.html
{% extends '2024/base.html' %}
{% load humanize %}


{% block content %}
<h1> Filing Status </h1>
<h3> for debugging and QA </h3>

<div class="row">
{% if results %}
 
<div class="page-header row">
<div class="header-title">
</div>
</div>
<table class="table table-bordered table-striped">
    <tr>
        <th> Filing number </th>
        <th> Status </th>
        <th> Status create time </th>
        <th> Status update time </th>
        <th> Raw FEC link </th>
    </tr>

    {% for f in results %}
    <tr>
        <td> {{ f.filing_id }} </td>
        <td> {{ f.status }} </td>
        <td> {{ f.created }} </td>
        <td> {{ f.updated }} </td>
        <td> <a href='http://docquery.fec.gov/csv/{{f.filing_id|make_list|slice:"-3:"|join:""}}/{{f.filing_id}}.csv'>Download</a>
    </tr>
    {%endfor%}
</table>
</div>

{% include 'pagination.html' %}

{% endif %}

{% endblock %}

templates/2024/ies.html
{% extends '2024/base.html' %}
{% load humanize %}
{% load admin_urls %}


{% block content %}

<h2> Search for independent expenditures </h2>
<div class="row">
<form action="/2024/ies/" method="get">
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>


<div class="row">
{% if results %}
<div class="page-header row">
  <div class="header-title">
    {% if results_sum %}
    <h2> Independent Expenditures total: ${{results_sum.expenditure_amount__sum|floatformat:2|intcomma}} </h2>
    This total includes only itemized expenditures.
    {% endif %} 
    <div class="text-right">
        <a href="{{csv_url}}">Download as CSV</a>
    </div>

    </div>
</div>
  <table class="table table-bordered table-striped">
    <tr>
        <th> Committee </th>
        <th> Recipient name </th>
        <th> Address </th>
        <th> Purpose </th>
        <th> Candidate </th>
        <th> Race </th>
        {% if bloomberg_district %} <th> Cleaned district </th> {% endif %}
        <th> Support/Oppose</th>
        <th> Amount </th>
        <th> Date </th>
        <th> Form type</th>
    </tr>
    {% for result in results %}
    <tr>
        <td>{{result.committee_name}}</td>
        <td>{{result.payee_name}}</td>
        <td>{{result.address}}</td>
        <td>{{result.expenditure_purpose_descrip}}</td>
        <td>{{result.candidate_name}}</td>
        <td>{{result.district}}</td>
        {% if bloomberg_district %} <td> {{result.bloomberg_district}} (<a href="{% url opts|admin_urlname:'change' result.id%}">edit</a>) </td> {% endif %}
        <td>{{result.support}} </td>
        <td>${{result.expenditure_amount|floatformat:2|intcomma}}</td>
        <td>{{result.expenditure_date_formatted|date:"SHORT_DATE_FORMAT"}}</td>
        <td>{{result.filing_type}}</td>
    </tr>
  {% endfor %}
</table>
</div>

{% include 'pagination.html' %}

{% endif %}


{% endblock %}

templates/2024/index.html
{% extends '2024/base.html' %}
{% load humanize %}


{% block content %}

<h2> 2024 campaign finance </h2>

<p> <a href="{%url '2024:summary'%}">Summaries</a> </p>
<p> <a href="{%url '2024:contributions'%}">Contributions</a> </p>
<p> <a href="{%url '2024:expenditures'%}">Expenditures</a> </p>
<p> <a href="{%url '2024:ies'%}">Independent Expenditures</a> </p>
<p> <a href="{%url '2024:races'%}">Races</a> </p>
<p> <a href="{%url '2024:candidates'%}">Candidates</a> </p>
<p> <a href="{%url '2024:top_donors'%}">Top Donors</a> </p>

<h3> Admin </h3>
<p> <a href="{% url '2024:filing_status' 'failed'%}">Filings that failed to import</a></p>
{% endblock %}

templates/2024/races.html
{% extends '2024/base.html' %}
{% load humanize %}


{% block content %}

<h2> Races with IEs </h2>
<table class="table">
    <tr>
        <th> District </th>
        <th> Total IEs </th>
        <th> &nbsp; </th>
    </tr>
    {% for race in races %}
    <tr>
        <td> {{race.bloomberg_district}} </td>
        <td align="right"> ${{race.expenditure_amount__sum|floatformat:2|intcomma}}</td>

        <td> <a href="{%url '2024:ies'%}?bloomberg_district={{race.bloomberg_district}}">View district IEs</a></td>
    </tr>
    {% endfor %}
</table>
        

{% endblock %}

templates/2024/summary_001.html
{% extends '2024/base.html' %}
{% load humanize %}
{% load admin_urls %}


{% block content %}


<h2> Search for totals by reporting period </h2>
<h3>
{% if request.GET %}
<a href="{{ cycle_summary_url }}">(Repeat previous search for totals by cycle)
{% else %}
<a href="{{ cycle_summary_url }}">(Search instead for totals by cycle)
{% endif %}
</a>
</h3>
<div class="row">
<form action="/2024/summary/" method="get">
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>

<div class="row">
<div class="page-header row">
  <div class="header-title">
    <div class="text-right">
        <a href="{{csv_url}}"><p/>Download as CSV</a>
    </div>
    </div>
</div>

<table class="table">
    <tr>
        <th> Name </th>
        <th> Filing Type </th>
        <th> Coverage Period</th>
        <th> Individual<br/ >Contributions</th>
        <th> Disbursements </th>
        <th> Receipts </th>
        <th> Itemized<br/ >Contributions</th>
        <th> Unitemized<br/ >Contributions</th>
        <th title="Unitemized / Total Contributions * 100"> Percent<br/ >Unitemized<br/ >of Total</th>
        <th title="Disbursements / Receipts * 100"> Burn Rate </th>
        <th> Cash </th>
        <th> IEs </th>
        <th> Filing date </th>
    </tr>
    {% for filing in results %}
    <tr>
        <td> <a href="{%url '2024:committee' filing.filer_id%}">{{filing.committee_name}}</a> </td>
        <td> <a href="{{filing.url}}">{{filing.form}}</a> {% if filing.amends_filing %} (AMENDMENT) {% endif %} </td>
        <td> {% if filing.coverage_from_date|length == 8 %} {{filing.coverage_from_date|slice:"4:6"}}/{{filing.coverage_from_date|slice:"6:8"}}/{{filing.coverage_from_date|slice:"0:4"}} {% else %} {{filing.coverage_from_date}}{%endif%} - 
        {% if filing.coverage_through_date|length == 8 %} {{filing.coverage_through_date|slice:"4:6"}}/{{filing.coverage_through_date|slice:"6:8"}}/{{filing.coverage_through_date|slice:"0:4"}} {% else %} {{filing.coverage_through_date}}{%endif%}
        
        </td> 
        <td>${{filing.period_individual_contribution_total|floatformat:2|intcomma}} </td>
        <td> <a href="{%url '2024:expenditures'%}?filing_id={{filing.filing_id}}">${{filing.period_total_disbursements|floatformat:2|intcomma}}</a> </td>
        <td> <a href="{%url '2024:contributions'%}?filing_id={{filing.filing_id}}">${{filing.period_total_receipts|floatformat:2|intcomma}}</a>
            {% if filing.period_total_receipts > 99999 %}
                (<a href="{% url opts|admin_urlname:'changelist' %}?q={{filing.filing_id}}">Link donors</a>)
                
            {% endif %}
        </td>
        <td> ${{filing.period_individuals_itemized|floatformat:2|intcomma}} </td>
        <td> ${{filing.period_individuals_unitemized|floatformat:2|intcomma}} </td>
        <td> {{filing.period_percent_unitemized|floatformat:1|intcomma}}% </td>
        <td> {{filing.period_disbursements_div_receipts|floatformat:1|intcomma}}% </td>
        <td> ${{filing.cash_on_hand_close_of_period|floatformat:2|intcomma}} </td>
        <td> <a href="{%url '2024:ies'%}?filing_id={{filing.filing_id}}">
        {% if filing.form == 'F24' %}
          ${{filing.computed_ie_total_for_f24|floatformat:2|intcomma}}
        {% else %}
          ${{filing.period_independent_expenditures|floatformat:2|intcomma}}
        {% endif %}
        
        
    </a> </td>
        <td> {% if filing.date_signed|length == 8 %} {{filing.date_signed|slice:"4:6"}}/{{filing.date_signed|slice:"6:8"}}/{{filing.date_signed|slice:"0:4"}} {% else %} {{filing.date_signed}}{%endif%}</td>   
    </tr>
    {% endfor %}
</table>

{% include 'pagination.html' %}

        

{% endblock %}

templates/2024/top_donors.html
{% extends '2024/base.html' %}
{% load humanize %}
{% load admin_urls %}


{% block content %}

<h2> Top Donors </h2>
<h5> Includes only contributions that have been manually matched to a donor. Before using these numbers please contact {{contact}}</h5>
<table class="table">
    <tr>
        <th> Name </th>
        <th> Employer </th>
        <th> Contributions total </th>
        <th></th>

    </tr>
    {% for result in results %}
    <tr>
        <td> <a href="{%url 'donor:donor_details' result.id %}">{{result.bloomberg_name}}</a> </td>
        <td> {{result.bloomberg_employer}} </td>
        <td>
        {%if result.contribution_total_2024 > 0 %}
             ${{result.contribution_total_2024|floatformat:2|intcomma}}
        {%else%}
            No matched contributions
        {%endif%}
        </td>
        <td> <a href="{% url opts|admin_urlname:'change' result.id%}">Edit donor</a></td>
    </tr>
    {% endfor %}
</table>

{% include 'pagination.html' %}

        

{% endblock %}